### ISSUE TITLE
Any plan for new updates and releases? 

### ISSUE THREAD

**Issue by zcuric** [pd4d10/git-touch#13]
Hi, great app! I really like it, so much to be exact, that I went and looked into Dart and Flutter to learn to contribute to it. 

What are you plans for new releases? Will you keep updating?

**Comment by pd4d10** [comment]
Yes, It is being actively developed.

If you have any idea please submit an issue, I'm glad to discuss about it

**Comment by zcuric** [comment]
Very nice! I'm glad to hear that. 

I notice several things: 
- events are not implemented 
- markdown doesn't work, at least not on Android.

**Comment by pd4d10** [comment]
In the long term, we want to support more platforms other than GitHub, for example GitLab(#4) and Gitea(#5). These would require lots of work.

If you want to get started, I think #2 or #3 might be a good option

**Comment by zcuric** [comment]
Ok, nice, any suggestion for a good Flutter learning tutorial?

**Comment by pd4d10** [comment]
Oh, I'm not sure, probably [the official tutorial](https://flutter.dev/docs/reference/tutorials) is a good start?

**Comment by zcuric** [comment]
👍
