### ISSUE TITLE
[feature improvement] Allow language viewing

### ISSUE THREAD

**Issue by lcol3117** [pd4d10/git-touch#20]
On the github webpage for a repo, a colored bar is displayed that represents the amount of different languages the repo uses. On the web desktop version, clicking on it yields percentages and the languages, not just colors. Although this bar exists on the app, there is no way to see which languages the colors correspond to.

**Comment by pd4d10** [comment]
Hi, @lcol3117 , thanks for the feedback!

It should have been fixed in the latest v1.2.0. Please give it a try

**Comment by pd4d10** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-28 at 14 46 33](https://user-images.githubusercontent.com/9524411/73241448-fe1ac800-41dc-11ea-8a12-c66cfa91b329.png)

**Comment by lcol3117** [comment]
This is great! Thank you so much!
