### ISSUE TITLE
cannot view org reps

### ISSUE THREAD

**Issue by Lukas-Batema** [pd4d10/git-touch#25]
can you add this

**Comment by pd4d10** [comment]
Hi, @Lukas-Batema , it should have been fixed in v1.4.0. Thanks!

**Comment by Lukas-Batema** [comment]
Thanks, I didn’t see this until now :)

**Comment by Lukas-Batema** [comment]
@pd4d10 this issue seems to not be fixed... check the above issue mention for more info!
