### ISSUE TITLE
github OAuth doesn't work

### ISSUE THREAD

**Issue by iTrooz** [pd4d10/git-touch#291]
Immediately after installing the app, I tried to add a github account using OAuth (first option)
When I authorized the application through github, the application just returning to the "add an account" screen without adding the account

I then tried with a Personal Access Token, which worked fine. I then tried to add again the account with OAuth. This time, the account was added (and so I had two accounts, one with PAT and one with OAuth), but using it brings the following error (see screenshot)
![Screenshot_20221103-201518_GitTouch](https://user-images.githubusercontent.com/42669835/199813806-3b314625-2d3d-45aa-a417-0c3229199620.png)

**Comment by thomas-bouvier** [comment]
Hey, I think this has been fixed in https://github.com/git-touch/git-touch/releases/tag/v1.13.0

**Comment by iTrooz** [comment]
Indeed that fixed it ! Sorry I didn't check versions first
