### ISSUE TITLE
Contribution graph not displayed correctly on iPad

### ISSUE THREAD

**Issue by shreyas1599** [pd4d10/git-touch#38]
Contribution graph currently is aligned right on iPad in both Landscape and Portrait mode. Would look better if it is centred or aligned left. 

## Portrait 
![image](https://user-images.githubusercontent.com/28999492/74358376-5b229a80-4de7-11ea-9254-293ee2755006.png)

## Landscape
![image](https://user-images.githubusercontent.com/28999492/74358394-61b11200-4de7-11ea-8f81-9d65b771fd0f.png)

**Comment by pd4d10** [comment]
Nice catch!

Although iPad is already supported, it is not fully tested. Perhaps we need to redesign the iPad UI... But it seems to be a huge project.

>  Would look better if it is centred or aligned left.

Agreed with you.

**Comment by shreyas1599** [comment]
I could work on testing the iPad and fixing this and others I encounter. Other components looked fine so far, so I guess we won’t have to redesign it.
