### ISSUE TITLE
[UI problem]: iOS bold text.

### ISSUE THREAD

**Issue by evillt** [pd4d10/git-touch#7]
In iOS, the font looks a bit tight. Can we fix this?

### Bold text size:

![0AC80A85CF3C36043B9195F64AD39794](https://user-images.githubusercontent.com/19513289/66260091-a0f1a580-e7ec-11e9-912f-14ada10a58f3.JPG)

### Normal size:

![58B01C6CDF5A120035FFC56B3980F737](https://user-images.githubusercontent.com/19513289/66260101-bcf54700-e7ec-11e9-9538-11d56273f1d3.JPG)

**Comment by pd4d10** [comment]
@evillt Thanks! Could you please provide your iOS version?

Probably related to https://github.com/flutter/flutter/issues/41101

**Comment by evillt** [comment]
My mistake.

ios 13.1.2

Agree with "Probably related to flutter/flutter#41101"

**Comment by pd4d10** [comment]
Hi @evillt , GitTouch v1.2.0 is released, which is built with Flutter 1.12.13+hotfix (the latest stable version).

Seems there is still an issue (https://github.com/flutter/flutter/issues/43998).

If it is still not fixed, let's keep it open to track this

**Comment by evillt** [comment]
Awesome!
