### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by gluons** [pd4d10/git-touch#8]
I hope we can have dark mode in the future. 🙂

**Comment by pd4d10** [comment]
Yeah, we have already implemented it at master. But it is not finished yet.

**Comment by pd4d10** [comment]
It has been implemented in the latest v1.2.0, which supports both iOS and Android.

Thanks for your feedback!

/cc @gluons @AZn5ReD @Tydox

**Comment by gluons** [comment]
![Thank you](https://media.giphy.com/media/3oz8xIsloV7zOmt81G/giphy.gif)

**Comment by gluons** [comment]
There are some problems when use dark mode.

1. Token input is complete dark. Unable to see what I type in that input.
   ![Screenshot_2020-01-28-20-24-57-865_io github pd4d10 gittouch](https://user-images.githubusercontent.com/4688092/73319703-c14be100-426f-11ea-9522-47dddfc90d35.jpg)

2. Code theme picker is dark. Unable to see what I select.
   ![Screenshot_2020-01-28-20-26-44-841_io github pd4d10 gittouch](https://user-images.githubusercontent.com/4688092/73319826-1c7dd380-4270-11ea-9e1a-a4f29c85b337.jpg)

**Comment by pd4d10** [comment]
Thanks for your feedback!

I'm going to close this issue since dark mode is already implemented.

Let's track the issue of Android dark mode style in #22
