### ISSUE TITLE
Add repo name under issue name in the Toolbar

### ISSUE THREAD

**Issue by anticafe** [pd4d10/git-touch#9]
![image](https://user-images.githubusercontent.com/340836/66710054-20f2af00-ed9b-11e9-839b-1e9ffd78432c.png)

When I open the issue detail, it's hard to know which repo it belongs to. Thus, I suggest you add the repo name as subtitle of the Toolbar.

**Comment by pd4d10** [comment]
It's reasonable. But if the repo name is long enough, the whole title bar will be filled with text and seems be a little tight.

Probably we need a new UI design for it. Let's keep it open for more discussion.

**Comment by pd4d10** [comment]
Hi, @anticafe , it seems a bit wired to fill the title bar with repo name if it is too long. So we add a row to show this information. Does this meets your needs?

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-09 at 10 41 52](https://user-images.githubusercontent.com/9524411/74095267-621c8500-4b29-11ea-98c8-635461c571a4.png)

**Comment by anticafe** [comment]
Hi @pd4d10 Your new design looks nicer. 👍
